title: ikovylyaev
email: ikovylyaev@bk.ru
description: >- 
  i am ivan kovylyaev. freelance ui/ux and graphic designer from saint-petersburg, russia. currently working on finka design system. if you want to work with me, please contact me by one of the links below.
  
baseurl: ""
url: "https://ikovylyaev.com"

theme: minima
plugins:
  - jekyll-feed

collections:
  design:
    output: true
    order:
      - 12.md
      - 13.md
      - 8.md
      - 9.md
      - 10.md
      - 14.md
      - 15.md
      - 16.md
      - 7.md
      - 6.md
      - 5.md
      - 20.md
      - 17.md
      - 4.md
      - 18.md
      - 2.md
      - 1.md
      - 3.md
      - 11.md
