title: ikovylyaev
email: ikovylyaev@bk.ru
description: >- 
  i am ivan kovylyaev. freelance ui/ux and graphic designer from saint-petersburg, russia. currently working on greentech faculty of itmo university. if you want to work with me, please contact me by one of the links below.
  
baseurl: ""
url: "https://ikovylyaev.com"

theme: minima
plugins:
  - jekyll-feed

collections:
  design:
    output: true
    sort_by: id
